include:
  - board: seeeduino_xiao_ble
    shield: peks48_r
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: peks48_l
  - board: seeeduino_xiao_ble
    shield: settings_reset
